### ISSUE TITLE
Option to populate fields before save/update to ES

### ISSUE THREAD

**Issue by alexkavon** [mongoosastic/mongoosastic#90] opened 2015-07-08 23:23 UTC
Mongoose makes Mongo relational. I have documents in my db that have a reference field like so:

```
{
    "_id" : ObjectId("545a853ab1d3e0a807cc1466"),
    "name" : "Amber Waves of Grain",
    "business" : ObjectId("5458050584798670186ebeb7"),
    "created" : ISODate("2014-11-05T20:14:50.343Z"),
    "updated" : ISODate("2015-07-08T22:40:00.022Z")
}
```

The "business" reference field is specified in the schema like so:

```
business: {type: mongoose.Schema.Types.ObjectId, ref: 'Business', required: required}
```

This works well for mongoose and mongo since I can just populate that data with a .populate() on my query. However I need to store the ES document with a business field that looks like this:

```
{
  "_source": {
    "name": "Amber Waves of Grain",
    "business": {
      "_id": ObjectId("5458050584798670186ebeb7"),
      "name": "Bob's Business"
    }
  }
}
```

Is this currently possible? If not it would be nice to have an option to specify which fields need to be populated before save to ES.

**Comment by MichaelBoselowitz** [comment] 2015-07-22 16:38
This seems like a duplicate of #8. However, I would very much like to see this implemented as well. I need this feature for my current project.

I may end up posting a pull request eventually.

**Comment by reilg** [comment] 2015-08-18 08:11
Was there any progress on this?

**Comment by moooji** [comment] 2015-08-31 11:06
+1 for implementing this. Should be solvable by doing something like 

`var populated = model.populate('fieldToPopulate');`

in the serialize method https://github.com/mongoosastic/mongoosastic/blob/master/lib/serialize.js or? I can give it a shot later and maybe send a PR if it works. The question is how to select which fields to populate and which not? Maybe `es_populate: true`?

 http://mongoosejs.com/docs/api.html#document_Document-populate

**Comment by moooji** [comment] 2015-08-31 13:24
Or probably nicer to populate the document in the "post" hook.

```
schema.post('save', function(doc) {

   // Populate the doc
   doc.populate('somePathToPopulate', function (err, doc) {

      // Handle errors...
      if(err) throw err;

      // Index the populated document
      doc.index(function(err, res) {
         if (!filter || !filter(doc)) {
            doc.emit('es-indexed', err, res);
         }
      });
   });
});
```

**Comment by gsantome** [comment] 2015-10-14 19:17
@moooji Thanks for your idea... I want to do exactly the same of what you need but can I ask you what is "filter"?  That idea works for you?
Thanks!

**Comment by isayme** [comment] 2016-12-25 14:49
@alexkavon the feature is supported now ~

PR: https://github.com/mongoosastic/mongoosastic/pull/147
Document: https://github.com/mongoosastic/mongoosastic#indexing-mongoose-references

**Closed by isayme** 2016-12-25 14:49 UTC
Labels: enhancement
