### ISSUE TITLE
Error plugin mongoosastic with schema has attribute of type array of objects

### ISSUE THREAD

**Issue by basimhennawi** [mongoosastic/mongoosastic#275] opened 2017-01-19 14:39 UTC
When I got schema that contains attribute of type array of objects, i got an error on hooking the schema with `mongoosastic` plugin
 ```
 let productSchema = new Schema({
    slug: {type: String, es_indexed: true},
    i18n: [{
      locale: {type: String, required: true},
      title: {type: String, es_indexed: true},
    }],
  });
  productSchema.plugin(mongoosastic);
```

My error stack is as follow:

![image](https://cloud.githubusercontent.com/assets/10829464/22110804/b9e887fe-de65-11e6-8fc2-1902ba9bad3d.png)

When I either comment the plugin line or the complex attribute, it works..
Any help is appreciated, thanks in advance!

**Comment by isayme** [comment] 2017-01-19 14:58
cannot reproduce with mongoosastic 4.2.4.

what's your mongoose & mongoosastic version ? 

and please show us more code if you can~

**Comment by basimhennawi** [comment] 2017-01-19 15:11
Here you go `mongoosastic` and `mongoose` version:
```    
"mongoosastic": "^4.2.4",
"mongoose": "^4.7.7",
```
Please advise which code you want me to show that may relate to.

**Comment by isayme** [comment] 2017-01-20 13:45
sorry, I cannot reproduce on my side.

have you try reinstall the package? or could you try to debug the reason ?

**Comment by danielstaleiny** [comment] 2017-02-02 21:42
@basimhennawi
Check your code semantics before creating new issue.  

```
let productSchema = new Schema({
  slug: { type: String, es_indexed: true },
  i18n: [{
    locale: { type: String, required: true },
    title: { type: String, es_indexed: true },
  }]
});
```

You have one extra closing parenthesis in your schema definition and one extra comma.

**Comment by basimhennawi** [comment] 2017-02-05 15:00
@danielstaleiny Regarding the:
- Extra closing parenthesis, it's a typo just here in the issue (thanks for mentioning it)
- Trailing commas in JavaScript, it's okay, see more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)

**Closed** 2018-12-18 10:34 UTC
