### ISSUE TITLE
Remove document form elasticsearch using filters

### ISSUE THREAD

**Issue by panceri** [mongoosastic/mongoosastic#110] opened 2015-09-30 13:41 UTC
I have a filter to index only documents in elasticsearch when flagged with lost == true. It's working when this flag is true but when i update with flag == false this document still in there.

**Comment by michaek** [comment] 2016-03-10 18:33
I haven't tested it yet, but it looks like https://github.com/mongoosastic/mongoosastic/pull/130 has resolved this.

**Comment by michaek** [comment] 2016-03-10 18:56
Yes, that does appear to work as designed.

**Comment by isayme** [comment] 2016-12-26 10:19
@michaek can  we close this issue ?

**Comment by michaek** [comment] 2016-12-26 14:34
@isayme I didn't open this issue, but it appears to me it can be closed.

**Closed** 2016-12-26 14:40 UTC
